
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [ 'functions',
      'deploy',
      '$_FUNC_NAME',
      '--runtime',
      'python39',
      '--entry-point',
      'app',
      '--source',
      'https://source.developers.google.com/projects/fizzbuzz-example/repos/fizz-buzz-flask-example/moveable-aliases/master/paths//',
      '--trigger-http',
      '--allow-unauthenticated'
    ]
